
export const LOAD_MOVIES_FAILED = 'MOVIES/LOAD/FAILED'
export const LOAD_MOVIES_SUCCESS = 'MOVIES/LOAD/SUCCEEDED';
export const LOAD_DETAILMOVIES_SUCCESS = 'DETAILMOVIES/LOAD/SUCCEEDED';
export const LOAD_DETAILMOVIES_FAILED = 'DETAILMOVIES/LOAD/FAILED';